### ISSUE TITLE
System Fonts

### ISSUE THREAD

**Issue by exkpwn** [CatogramX/CatogramX#1]
not a bug

it's a request actually

would you please reconsider not removing system fonts feature

i mean if it doesn't follow system fonts it uses roboto for titles and system fonts for chats and texts

kinda inconsistent in Samsung devices and custom roms using different system fonts.

**Comment by nift4** [comment]
> would you please reconsider not removing system fonts feature

well, as I wrote in the commit message, it was pretty damn buggy and also making the italic font bold even though it wasn't supposed ti... well, those problems are on the system side, and I can't fix those, but I was getting a ton of bug reports... best I can do is a switch, I'll add that to the backlog

**Comment by exkpwn** [comment]
thanks
that's all I ask.

**Comment by nift4** [comment]
added
