### ISSUE TITLE
translation problem

### ISSUE THREAD

**Issue by TeaqariaWTF** [CatogramX/CatogramX#3]
It does not translate the articles shared with the photos at the first time, it is necessary to try more than once

Video Link : https://gofile.io/d/MWhe0v

**Comment by nift4** [comment]
-> see chat

**Comment by TeaqariaWTF** [comment]
> 

 I did not understand what you said

**Comment by nift4** [comment]
tap on the left of a message and tap translate

**Comment by TGRush** [comment]
> tap on the left of a message and tap translate

dude I think he has no idea what you mean as this is quite simplified English that his translator doesn't properly handle ._.
